### ISSUE TITLE
I think that this is overdeveloped

### ISSUE THREAD

**Issue by fregante** [jhardy/compass-ceaser-easing#12]
Why do you need Compass and all those functions for something that could be easily defined as:

```
//_easings.scss: https://github.com/thoughtbot/bourbon/blob/master/app/assets/stylesheets/addons/_timing-functions.scss
$ease-in-quad:      cubic-bezier(0.550,  0.085, 0.680, 0.530);
…
```

And:

```
//your-style.scss:
@import easings.scss
transition: opacity 1s $ease-in-quad;
```

It's a single _definition_ file with variables that can be used directly.
What does `compass-ceaser-easing` offer over this approach (other than complexity)?

**Comment by jhardy** [comment]
You are right this doesn't need to be a compass only extension and I should get around to making that an optional feature. 

The way this is developed is because I created it for the way I like to work. For me having a function return the value like `ceaser($easeInSine)` instead of relying on a variable is a better approach for my workflow, especially when working on a team and a large codebase. The function lets you know you are using a library and not a set of variables defined elsewhere. 

Thanks for the feedback.
